mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),


    url(r'^accounts/login/$',views.login, name='login', kwargs={'template_name': 'login.html'}),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

    url(r'', include('article.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/article/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from sorl.thumbnail import ImageField

# Create your models here.

class article(models.Model):
    author = models.ForeignKey('auth.User', null=True)
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=50, blank=False)
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    visit = models.IntegerField(default=0)
    image = models.ImageField(upload_to='temp/img/', null=True)
    is_draft = models.BooleanField(default=False)


    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-publish_date']

mysite/mysite/templates/article_detail.html
{% extends 'base.html' %}
{% load custom_markdown %}

{% block content %}
<div class="row" style="background-color:white; padding: 15px;">
    <h1>{{ article.title }}</h1>

                <!-- Author -->
    <p class="lead">
        作者：  <a href="#">{{ article.author }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> 发表于 {{ article.publish_date }} {% load disqus_tags %}
<a href="{{ object.get_absolute_url }}#disqus_thread">View Comments</a>
{% disqus_num_replies %}
        {% if user.is_authenticated %}
        <a href="/edit_article/{{article.id}}">编辑</a>
        {% endif %}
    </p>

    <hr>
    <p class="lead"> {{ article.content|custom_markdown}}</p>
    <hr>
</div>
<hr>
<div class="row" style="background-color:white; padding: 15px;">
{% disqus_show_comments %}
</div>
{% endblock %}
{% block cate %}
{% for cate in category_list %}
    <li><a href="/category/{{ cate }}"><span>{{ cate }}</span></a>
    </li>
{% endfor %}
{% endblock %}

mysite/mysite/templates/article_detail2.html
{% extends 'base.html' %}
{% load custom_markdown %}

{% block content %}
    <h1>{{ article.title }}</h1>

                <!-- Author -->
    <p class="lead">
        作者：  <a href="#">{{ article.author }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> 发表于 {{ article.publish_date }} {% load disqus_tags %}
<a href="{{ object.get_absolute_url }}#disqus_thread">View Comments</a>
{% disqus_num_replies %}</p>

    <hr>
    <p class="lead"> {{ article.content|custom_markdown}}</p>
    <hr>

{% disqus_show_comments %}
{% endblock %}
{% block cate1 %}
{% for cate in category_list %}
    {% if forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

{% block cate2 %}
{% for cate in category_list %}
    {% if not forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

mysite/mysite/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href=" {% static 'css/blog-post.css' %}" rel="stylesheet">

    <!--<link href=" {% static 'css/vim.css' %}" rel="stylesheet">-->
    <script src="{% static 'highlight/highlight.pack.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'highlight/styles/zenburn.css' %}">

    <link href="{% static 'kindeditor/themes/default/default.css' %}" rel="stylesheet" />
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Lanny105的博客</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">关于我</a>
                    </li>
                    <li>
                        <a href="/">服务</a>
                    </li>
                    <li>
                        <a href="/">联系</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="/new_article">新日志</a>
                    </li>
                    <li>
                        <a href="/draft_list">草稿</a>
                    </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                    {% if user.is_authenticated %}

                        <a href="{% url 'logout' %}">登出</a>

                    {% else %}
                        <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock">登录</span></a>
                    {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <!--<h1>最新日志</h1>-->

            <div class="col-lg-8">

            {% block content %}

            {% endblock %}

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input id = "search" type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button" onclick="mySearch();">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>


                    <!--<div class="row">-->
                        <!--<div class="col-lg-6">-->
                            <!--<ul class="list-unstyled">-->
                                <!--{% block cate1 %}-->

                                <!--{% endblock %}-->

                            <!--</ul>-->
                        <!--</div>-->
                        <!--<div class="col-lg-6">-->
                            <!--<ul class="list-unstyled">-->
                                <!--{% block cate2 %}-->

                                <!--{% endblock %}-->
                            <!--</ul>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!-- /.row -->
                    <div class="tagcloud06">
                        <ul>
                        {% block cate %}

                        {% endblock %}
                        </ul>
                    </div>

                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>最新回复</h4>
                    {% load disqus_tags %}
                                    <!--{% disqus_recent_comments shortname num_items excerpt_length hide_avatars avatar_size %}-->
                    {% disqus_recent_comments shortname 5 50 0 32 %}
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src= "{% static 'js/jquery.js' %}" ></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

    <script id="dsq-count-scr" src="//lanny105.disqus.com/count.js" async></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>
        var csrfitems = document.getElementsByName("csrfmiddlewaretoken");
        var csrftoken = "";
        if(csrfitems.length > 0)
        {
            csrftoken = csrfitems[0].value;
        }
        var mySearch = function () {
            $(location).attr('href', '/search/' + $('#search').val())
        }
        KindEditor.ready(function(K) {
            window.editor = K.create('#id_content', {
                uploadJson: '/uploadImg/',
                extraFileUploadParams : {
                    csrfmiddlewaretoken:csrftoken
                },
            });
        });
    </script>

</body>

</html>

mysite/mysite/templates/base2.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href=" {% static 'css/blog-post.css' %}" rel="stylesheet">

    <link href=" {% static 'css/signin.css' %}" rel="stylesheet">

    <link href="{% static 'kindeditor/themes/default/default.css' %}" rel="stylesheet" />
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->
    <style type="text/css">.thumb-image{float:left;width:300px;position:relative;padding:5px;}</style>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Lanny105的博客</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">关于我</a>
                    </li>
                    <li>
                        <a href="/">服务</a>
                    </li>
                    <li>
                        <a href="/">联系</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="/new_article">新日志</a>
                    </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                    {% if user.is_authenticated %}

                        <a href="{% url 'logout' %}">登出</a>

                    {% else %}
                        <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock">登录</span></a>
                    {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src= "{% static 'js/jquery.js' %}" ></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

    <script>
        var csrfitems = document.getElementsByName("csrfmiddlewaretoken");
        var csrftoken = "";
        if(csrfitems.length > 0)
        {
            csrftoken = csrfitems[0].value;
        }
        var mySearch = function () {
            $(location).attr('href', '/search/' + $('#search').val())
        }
        KindEditor.ready(function(K) {
            window.editor = K.create('#id_content', {
                uploadJson: '/uploadImg/',
                extraFileUploadParams : {
                    csrfmiddlewaretoken:csrftoken
                },
            });
        });
    </script>

<script>

$(document).ready(function() {
        $("#image-holder").append('<img class = thumb-image src="' + $('#img').attr("name") + '">');
        $("#fileUpload").on('change', function() {
          //Get count of selected files
          var countFiles = $(this)[0].files.length;
          var imgPath = $(this)[0].value;
          var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
          var image_holder = $("#image-holder");
          image_holder.empty();
          if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
            if (typeof(FileReader) != "undefined") {
              //loop for each file selected for uploaded.
              for (var i = 0; i < countFiles; i++)
              {
                var reader = new FileReader();
                reader.onload = function(e) {
                  $("<img />", {
                    "src": e.target.result,
                    "class": "thumb-image"
                  }).appendTo(image_holder);
                }
                image_holder.show();
                reader.readAsDataURL($(this)[0].files[i]);
              }
            } else {
              alert("This browser does not support FileReader.");
            }
          } else {
            alert("Pls select only images");
          }
        });

      });
</script>

</body>

</html>

mysite/mysite/templates/index.html
{% extends 'base.html' %}
{% load custom_markdown %}
{% load widget_tweaks %}
<!--{% load thumbnail %}-->


{% block content %}
{% for post in article_list.object_list %}


    <div class="row" id="post">
        <div class="row">
        <div class="col-md-4">
        <div class="parent" onclick="">
            <div class="child">
            <a class = "thumbnail" href="/article/{{ post.id }}" style="margin-bottom:0px;">
                {% thumbnail post.image "250x200" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            </a>
            </div>
        </div>
        </div>

        <div class="col-md-8">

            <h3 style="margin-bottom: 15px;"><a class="header" href="/article/{{ post.id }}">{{ post.title }}</a> <a style="font-size:16px" class = "btn btn-info btn-xs" href="/category/{{ post.category }}">{{ post.category }}</a> </h3>

            <p style="color: #9b9b9b; margin-right: 15px;">{{ post.content | safe | striptags | truncatechars:200 }}</p>

            <p> <a href="/article/{{ post.id }}">阅读全文</a>
                <a href="{{ object.get_absolute_url }}/article/{{post.id}}/#disqus_thread"  >View Comments</a>
                {% if user.is_authenticated %}
                    <a href="/edit_article/{{post.id}}">编辑</a>
                {% endif %}
            </p>
        </div>
        </div>
        <div class="row">
            <hr class="tag_hr">
            <p class="tag"><span class="glyphicon glyphicon-user">{{ post.author }}</span> 发表于: <span class="glyphicon glyphicon-time"></span> {{ post.publish_date }} 浏览<span class="badge">{{ post.visit }}</span> </p>

        </div>

    </div>
    <hr style="margin-top: 10px; margin-bottom: 10px">

{% endfor %}

{% load i18n %}
<div class="pagination">
    <nav aria-label="Page navigation">
    <ul class="pagination">

    {% if article_list.has_previous %}
        <li>
        <a href="?{{ article_list.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
    {% else %}
        <li class="disabled">
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
        </li>
    {% for page in article_list.pages %}

        {% if page %}
            {% ifequal page article_list.number %}
            <li class="active">
                <span class="current page">{{ page }}</span>
            {% else %}
            <li>
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
            </li>
        {% else %}
        <li>
            <span>...</span>
        </li>
        {% endif %}
    {% endfor %}

    {% if article_list.has_next %}
        <li>
        <a href="?{{ article_list.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <li class="disabled">
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
        </li>
    </ul>
    </nav>
</div>
{% endblock %}


{% block cate %}
{% for cate in category_list %}
    <li><a href="/category/{{ cate }}"><span>{{ cate }}</span></a>
    </li>
{% endfor %}
{% endblock %}

mysite/mysite/templates/index2.html
{% extends 'base.html' %}
{% load custom_markdown %}
{% load widget_tweaks %}
<!--{% load thumbnail %}-->


{% block content %}
{% for post in article_list %}




    <div class="row" id="post">
        <div class="row">
        <div class="col-md-4">
            <a href="/article/{{ post.id }}" class="thumbnail" style="margin-top: 20px;">
                {% thumbnail post.image "250x200" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            </a>
        </div>

        <div class="col-md-8">

            <h3 style="margin-bottom: 15px;">{{ post.title }} <a href="/category/{{ post.category }}" style="font-size: 20px;"><span class="label label-info">{{ post.category }}</span></a> </h3>

            <p style="color: #9b9b9b; margin-right: 15px;">{{ post.content | safe | striptags | truncatechars:200 }}</p>

            <p> <a href="/article/{{ post.id }}">阅读全文</a>
                <a href="{{ object.get_absolute_url }}/article/{{post.id}}/#disqus_thread"  >View Comments</a>
                {% if user.is_authenticated %}
                    <a href="/edit_article/{{post.id}}">编辑</a>
                {% endif %}
            </p>
        </div>
        </div>
        <div class="row">
            <hr class="tag_hr">
            <p class="tag"><span class="glyphicon glyphicon-user">{{ post.author }}</span> 发表于: <span class="glyphicon glyphicon-time"></span> {{ post.publish_date }} 浏览<span class="badge">{{ post.visit }}</span> </p>

        </div>

    </div>
    <hr>

{% endfor %}
{% endblock %}

{% block cate1 %}
{% for cate in category_list %}
    {% if forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

{% block cate2 %}
{% for cate in category_list %}
    {% if not forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

<h1 class="page-header">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>

                <!-- First Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

mysite/mysite/templates/login.html
{% extends "base2.html" %}
{% load widget_tweaks %}

{% block content %}

    <form method="post" action="{% url 'login' %}" class="form-signin"> {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label class="sr-only">username</label>
        <!--{{ form.username }}-->
        <!--<input type="text" class="form-control" placeholder="Username" required autofocus>-->

        {{ form.username | append_attr:"class:form-control" | attr:"type:text" | attr:"placeholder:Username" }}

        <label class="sr-only">Password</label>

        {{ form.password | append_attr:"class:form-control" | attr:"type:password" | attr:"placeholder:Password" }}

        <!--<input type="password" class="form-control" placeholder="Password" required>-->
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="login">Sign in</button>


        {% if form.errors %}
            <div class="alert alert-warning">
              <strong>Warning!</strong> Your username and password didn't match. Please try again.
            </div>
        {% endif %}
        <!--<table>-->
        <!--<tr>-->
            <!--<td>{{ form.username.label_tag }}</td>-->
            <!--<td>{{ form.username }}</td>-->
        <!--</tr>-->
        <!--<tr>-->
            <!--<td>{{ form.password.label_tag }}</td>-->
            <!--<td>{{ form.password }}</td>-->
        <!--</tr>-->
        <!--</table>-->

        <!--<input type="submit" value="login" />-->
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

{% block cate1 %}
{% for cate in category_list %}
    {% if forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

{% block cate2 %}
{% for cate in category_list %}
    {% if not forloop.counter0|divisibleby:"2"  %}
        <li><a href="/category/{{ cate }}">{{ cate }}</a>
        </li>
    {% endif %}
{% endfor %}
{% endblock %}

mysite/mysite/templates/new_article.html
{% extends 'base2.html' %}
{% load widget_tweaks %}


{% block content %}


    <h1></h1>

    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        <div class="col-md-4">
            <div class="form-group">
                  <label>Title:</label>
                  {{ form.title | append_attr:"class:form-control"}}
            </div>
            <div class="form-group">
                  <label>Category:</label>
                  {{ form.category | append_attr:"class:form-control"}}
            </div>

            <div class="form-group">
                  <label>是否存为草稿:</label>
                  {{ form.is_draft | append_attr:"class:form-control"}}
            </div>

            <div class="form-group">
                  <label>Image:</label>
                  <!--<input type="file" class="form-control">-->
                  {{ form.image | append_attr:"class:form-control" | attr:"id:fileUpload"}}

                <div id="img" name="{{ form.image.value.url }}"></div>

            </div>
            <div class="form-group">
                <div id="image-holder"></div>
            </div>

        </div>
        <div class="col-md-8">
          <div class="form-group">
              <label>Content:</label>
              {{ form.content | append_attr:"class:form-control" | attr:"rows:28"}}
          </div>
            <span style="float: right"><button type="submit" class="btn btn-primary" >Submit</button>
            <a class="btn btn-default" href="/" role="button" >Cancel</a></span>

        </div>
    </form>

{% endblock %}